apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: podinfo
  namespace: infrastructure-engineering
  labels:
    app: podinfo
spec:
  selector:
    matchLabels:
      app: podinfo
  targetLabels:
    - zone
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
